# This is a basic workflow to help you get started with Actions

name: Make Extension Archives

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Prepare V2 Archive
        run: |
          mv manifest.v2.json manifest.json
          mkdir v2
          mv ContentScripts/ img/ manifest.json v2

      - name: Prepare V3 Archive
        run: |
          mv manifest.v3.json manifest.json
          mkdir v3
          mv ContentScripts/ img/ manifest.json v3
          
      - name: Upload V2 Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: V2
          path: v2
          
      - name: Upload V3 Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: V3
          path: v3
