# This is a basic workflow to help you get started with Actions

name: Make Extension Archives

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Make V2 Archive
        run: |
          mv manifest.v2.json manifest.json
          zip V2.zip ContentScripts/ img/ manifest.json

      - name: Make V3 Archive
        run: |
          mv manifest.v3.json manifest.json
          zip V3.zip ContentScripts/ img/ manifest.json
          
      - name: Upload V2 Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: V2
          path: V2.zip
          
      - name: Upload V3 Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: V3
          path: V3.zip
